### ISSUE TITLE
We need this finished

### ISSUE THREAD

**Issue by ghost** [beakeyz/dadjoke-gen#1]
We need this finished

**Comment by beakeyz** [comment]
Welp, you leave me no choice. I have been busy with other (private) projects lately, but this is actually way more fun to develop then all those other things. I honestly don't know when I'll call it finished, but eh. Don't get a brain tumor from reading my crap-code btw

**Comment by ghost** [comment]
I will try _not_ to get a brain tumor at your wish. I do want to see this finished one day.
